local TITLE_PACK_GAMEPASS_ID = 1797105034

local TitleConfig = {}

TitleConfig.DEFAULT_TITLE_ID = "new_here"
TitleConfig.TITLE_PACK_GAMEPASS_ID = TITLE_PACK_GAMEPASS_ID

TitleConfig.titles = {
	new_here = {
		id = "new_here",
		display = "new here",
		category = "level",
		effect = "none",
		tintColor = Color3.fromRGB(255, 245, 235),
		levelRequired = 1,
	},
	settling_in = {
		id = "settling_in",
		display = "settling in",
		category = "level",
		effect = "none",
		tintColor = Color3.fromRGB(255, 245, 235),
		levelRequired = 5,
	},
	still_here = {
		id = "still_here",
		display = "still here",
		category = "level",
		effect = "none",
		tintColor = Color3.fromRGB(245, 235, 215),
		levelRequired = 10,
	},
	quiet_one = {
		id = "quiet_one",
		display = "quiet one",
		category = "level",
		effect = "none",
		tintColor = Color3.fromRGB(245, 235, 215),
		levelRequired = 20,
	},
	slow_steps = {
		id = "slow_steps",
		display = "slow steps",
		category = "level",
		effect = "tint",
		tintColor = Color3.fromRGB(235, 220, 180),
		levelRequired = 35,
	},
	familiar_face = {
		id = "familiar_face",
		display = "familiar face",
		category = "level",
		effect = "tint",
		tintColor = Color3.fromRGB(235, 220, 180),
		levelRequired = 50,
	},
	low_light = {
		id = "low_light",
		display = "low light",
		category = "level",
		effect = "tint",
		tintColor = Color3.fromRGB(225, 200, 155),
		levelRequired = 75,
	},
	half_awake = {
		id = "half_awake",
		display = "half awake",
		category = "level",
		effect = "shimmer",
		tintColor = Color3.fromRGB(215, 190, 140),
		levelRequired = 100,
	},
	soft_hours = {
		id = "soft_hours",
		display = "soft hours",
		category = "level",
		effect = "shimmer",
		tintColor = Color3.fromRGB(220, 190, 175),
		levelRequired = 150,
	},
	worn_in = {
		id = "worn_in",
		display = "worn in",
		category = "level",
		effect = "shimmer",
		tintColor = Color3.fromRGB(210, 180, 150),
		levelRequired = 200,
	},
	deep_water = {
		id = "deep_water",
		display = "deep water",
		category = "level",
		effect = "pulse",
		tintColor = Color3.fromRGB(170, 200, 200),
		levelRequired = 300,
	},
	long_shadow = {
		id = "long_shadow",
		display = "long shadow",
		category = "level",
		effect = "pulse",
		tintColor = Color3.fromRGB(180, 185, 195),
		levelRequired = 400,
	},
	cathedral_dark = {
		id = "cathedral_dark",
		display = "cathedral dark",
		category = "level",
		effect = "pulse",
		tintColor = Color3.fromRGB(195, 170, 145),
		levelRequired = 500,
	},
	fading_signal = {
		id = "fading_signal",
		display = "fading signal",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(200, 200, 210),
		levelRequired = 700,
	},
	last_one_here = {
		id = "last_one_here",
		display = "last one here",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(220, 205, 160),
		levelRequired = 1000,
	},
	after_everything = {
		id = "after_everything",
		display = "after everything",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(200, 190, 180),
		levelRequired = 1500,
	},
	gone_quiet = {
		id = "gone_quiet",
		display = "gone quiet",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(210, 205, 195),
		levelRequired = 2000,
	},
	nowhere_else = {
		id = "nowhere_else",
		display = "nowhere else",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(195, 200, 210),
		levelRequired = 3000,
	},
	end_of_the_hall = {
		id = "end_of_the_hall",
		display = "end of the hall",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(200, 170, 140),
		levelRequired = 5000,
	},
	always_was_here = {
		id = "always_was_here",
		display = "always was here",
		category = "level",
		effect = "glow",
		tintColor = Color3.fromRGB(225, 200, 165),
		levelRequired = 10000,
	},
	first_step = {
		id = "first_step",
		display = "first step",
		category = "exploration",
		effect = "none",
		tintColor = Color3.fromRGB(200, 220, 200),
		zoneId = "first_zone_discovered",
	},
	went_inside = {
		id = "went_inside",
		display = "went inside",
		category = "exploration",
		effect = "none",
		tintColor = Color3.fromRGB(190, 195, 200),
		zoneId = "cave_entrance",
	},
	further_in = {
		id = "further_in",
		display = "further in",
		category = "exploration",
		effect = "tint",
		tintColor = Color3.fromRGB(170, 180, 195),
		zoneId = "deep_cave_area",
	},
	above_it_all = {
		id = "above_it_all",
		display = "above it all",
		category = "exploration",
		effect = "tint",
		tintColor = Color3.fromRGB(200, 210, 225),
		zoneId = "rooftop",
	},
	found_something = {
		id = "found_something",
		display = "found something",
		category = "exploration",
		effect = "shimmer",
		tintColor = Color3.fromRGB(215, 200, 180),
		zoneId = "hidden_room",
	},
	everywhere_once = {
		id = "everywhere_once",
		display = "everywhere once",
		category = "exploration",
		effect = "pulse",
		tintColor = Color3.fromRGB(210, 200, 170),
		zoneId = "all_current_zones",
	},
	one_hour_in = {
		id = "one_hour_in",
		display = "one hour in",
		category = "presence",
		effect = "none",
		tintColor = Color3.fromRGB(255, 245, 235),
		hoursRequired = 1,
	},
	losing_track = {
		id = "losing_track",
		display = "losing track",
		category = "presence",
		effect = "none",
		tintColor = Color3.fromRGB(245, 235, 215),
		hoursRequired = 3,
	},
	no_rush = {
		id = "no_rush",
		display = "no rush",
		category = "presence",
		effect = "tint",
		tintColor = Color3.fromRGB(230, 220, 200),
		hoursRequired = 8,
	},
	full_day = {
		id = "full_day",
		display = "full day",
		category = "presence",
		effect = "tint",
		tintColor = Color3.fromRGB(220, 200, 175),
		hoursRequired = 24,
	},
	three_days_deep = {
		id = "three_days_deep",
		display = "three days deep",
		category = "presence",
		effect = "shimmer",
		tintColor = Color3.fromRGB(215, 195, 185),
		hoursRequired = 72,
	},
	a_whole_week = {
		id = "a_whole_week",
		display = "a whole week",
		category = "presence",
		effect = "pulse",
		tintColor = Color3.fromRGB(205, 195, 180),
		hoursRequired = 168,
	},
	not_going_anywhere = {
		id = "not_going_anywhere",
		display = "not going anywhere",
		category = "presence",
		effect = "glow",
		tintColor = Color3.fromRGB(210, 200, 165),
		hoursRequired = 500,
	},
	lived_here = {
		id = "lived_here",
		display = "lived here",
		category = "presence",
		effect = "glow",
		tintColor = Color3.fromRGB(200, 185, 160),
		hoursRequired = 1000,
	},
	said_something = {
		id = "said_something",
		display = "said something",
		category = "achievement",
		effect = "none",
		tintColor = Color3.fromRGB(210, 200, 220),
		achievementId = "said_something",
	},
	sat_down = {
		id = "sat_down",
		display = "sat down",
		category = "achievement",
		effect = "none",
		tintColor = Color3.fromRGB(215, 200, 180),
		achievementId = "sat_down",
	},
	left_a_mark = {
		id = "left_a_mark",
		display = "left a mark",
		category = "achievement",
		effect = "none",
		tintColor = Color3.fromRGB(190, 190, 200),
		achievementId = "left_a_mark",
	},
	came_back = {
		id = "came_back",
		display = "came back",
		category = "achievement",
		effect = "none",
		tintColor = Color3.fromRGB(225, 215, 200),
		achievementId = "came_back",
	},
	heard_them_all = {
		id = "heard_them_all",
		display = "heard them all",
		category = "achievement",
		effect = "shimmer",
		tintColor = Color3.fromRGB(200, 190, 215),
		achievementId = "heard_them_all",
	},
	knows_every_chair = {
		id = "knows_every_chair",
		display = "knows every chair",
		category = "achievement",
		effect = "tint",
		tintColor = Color3.fromRGB(210, 195, 175),
		achievementId = "knows_every_chair",
	},
	keeps_coming_back = {
		id = "keeps_coming_back",
		display = "keeps coming back",
		category = "achievement",
		effect = "tint",
		tintColor = Color3.fromRGB(225, 210, 180),
		achievementId = "keeps_coming_back",
	},
	part_of_the_walls = {
		id = "part_of_the_walls",
		display = "part of the walls",
		category = "achievement",
		effect = "shimmer",
		tintColor = Color3.fromRGB(195, 190, 185),
		achievementId = "part_of_the_walls",
	},
	up_too_late = {
		id = "up_too_late",
		display = "up too late",
		category = "achievement",
		effect = "shimmer",
		tintColor = Color3.fromRGB(180, 185, 210),
		achievementId = "up_too_late",
	},
	fell_asleep_here = {
		id = "fell_asleep_here",
		display = "fell asleep here",
		category = "achievement",
		effect = "tint",
		tintColor = Color3.fromRGB(190, 200, 215),
		achievementId = "fell_asleep_here",
	},
	one_of_us = {
		id = "one_of_us",
		display = "one of us",
		category = "achievement",
		effect = "tint",
		tintColor = Color3.fromRGB(220, 210, 195),
		achievementId = "one_of_us",
	},
	day_one = {
		id = "day_one",
		display = "day one",
		category = "achievement",
		effect = "pulse",
		tintColor = Color3.fromRGB(215, 185, 155),
		achievementId = "day_one",
	},
	hollow_night = {
		id = "hollow_night",
		display = "hollow night",
		category = "seasonal",
		effect = "pulse",
		tintColor = Color3.fromRGB(210, 180, 150),
		seasonStart = nil,
		seasonEnd = nil,
	},
	cold_quiet = {
		id = "cold_quiet",
		display = "cold quiet",
		category = "seasonal",
		effect = "shimmer",
		tintColor = Color3.fromRGB(190, 210, 225),
		seasonStart = nil,
		seasonEnd = nil,
	},
	been_a_year = {
		id = "been_a_year",
		display = "been a year",
		category = "seasonal",
		effect = "glow",
		tintColor = Color3.fromRGB(225, 210, 170),
		seasonStart = nil,
		seasonEnd = nil,
	},
	soft_spot = {
		id = "soft_spot",
		display = "soft spot",
		category = "seasonal",
		effect = "shimmer",
		tintColor = Color3.fromRGB(220, 200, 200),
		seasonStart = nil,
		seasonEnd = nil,
	},
	believer = {
		id = "believer",
		display = "believer",
		category = "gamepass",
		effect = "shimmer",
		tintColor = Color3.fromRGB(220, 210, 190),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
	quiet_donor = {
		id = "quiet_donor",
		display = "quiet donor",
		category = "gamepass",
		effect = "tint",
		tintColor = Color3.fromRGB(195, 215, 195),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
	black_glass = {
		id = "black_glass",
		display = "black glass",
		category = "gamepass",
		effect = "glow",
		tintColor = Color3.fromRGB(160, 160, 170),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
	soft_static = {
		id = "soft_static",
		display = "soft static",
		category = "gamepass",
		effect = "pulse",
		tintColor = Color3.fromRGB(195, 200, 220),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
	velvet_dark = {
		id = "velvet_dark",
		display = "velvet dark",
		category = "gamepass",
		effect = "glow",
		tintColor = Color3.fromRGB(180, 165, 185),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
	after_hours = {
		id = "after_hours",
		display = "after hours",
		category = "gamepass",
		effect = "shimmer",
		tintColor = Color3.fromRGB(185, 185, 205),
		gamepassId = TITLE_PACK_GAMEPASS_ID,
	},
}

TitleConfig.MIGRATION = {
	newcomer = "new_here",
	visitor = "settling_in",
	night_owl = "quiet_one",
	late_arrival = "quiet_one",
	local_title = "familiar_face",
	dim_room = "low_light",
	city_kid = "familiar_face",
	half_known = "familiar_face",
	regular = "familiar_face",
	slow_burn = "slow_steps",
	after_dark = "low_light",
	hush_hour = "soft_hours",
	socialite = "half_awake",
	stillwater = "soft_hours",
	spotlight = "half_awake",
	passing_lights = "worn_in",
	trendsetter = "worn_in",
	deep_end = "deep_water",
	downtown = "deep_water",
	night_bloom = "deep_water",
	runway = "long_shadow",
	blackglass = "long_shadow",
	icon = "cathedral_dark",
	cathedral_hush = "cathedral_dark",
	city_icon = "cathedral_dark",
	last_light = "fading_signal",
	neon_soul = "fading_signal",
	superstar = "last_one_here",
	prismatic = "last_one_here",
	divine = "after_everything",
	immortal = "gone_quiet",
	legend = "nowhere_else",
}

local levelTitleIds = {
	"new_here",
	"settling_in",
	"still_here",
	"quiet_one",
	"slow_steps",
	"familiar_face",
	"low_light",
	"half_awake",
	"soft_hours",
	"worn_in",
	"deep_water",
	"long_shadow",
	"cathedral_dark",
	"fading_signal",
	"last_one_here",
	"after_everything",
	"gone_quiet",
	"nowhere_else",
	"end_of_the_hall",
	"always_was_here",
}

local gamepassTitleIds = {
	"believer",
	"quiet_donor",
	"black_glass",
	"soft_static",
	"velvet_dark",
	"after_hours",
}

local function copyArray(source)
	local result = {}
	for index, value in ipairs(source) do
		result[index] = value
	end
	return result
end

function TitleConfig.GetTitle(titleId)
	return TitleConfig.titles[titleId]
end

function TitleConfig.GetTitleOrDefault(titleId)
	return TitleConfig.titles[titleId] or TitleConfig.titles[TitleConfig.DEFAULT_TITLE_ID]
end

function TitleConfig.GetLevelTitleIds()
	return copyArray(levelTitleIds)
end

function TitleConfig.GetGamepassTitleIds()
	return copyArray(gamepassTitleIds)
end

function TitleConfig.BuildPayload(titleId, newlyUnlocked)
	local title = TitleConfig.GetTitleOrDefault(titleId)

	return {
		equippedTitle = title.id,
		equippedDisplay = title.display,
		equippedEffect = title.effect,
		equippedTintColor = title.tintColor,
		newlyUnlocked = newlyUnlocked == true,
	}
end

return TitleConfig
